GET http://localhost:8880/book/list

###
GET http://localhost:8880/book/getList?name=教材&page=1&size=1


###
GET http://localhost:8880/book/queryList?name=教材&page=1&size=2


###

POST http://localhost:8880/book/save
Content-Type: application/json

{
  "name": "GO",
  "description": "GO 是最好的一门开发语言"
}

###
POST http://localhost:8880/book/delete?id=53479395351990272

###

POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###